---
title: "Sample Dashboard: Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```



```{r data_load}
data("instacart")
instacart_aisles = 
  instacart %>% 
  group_by(aisle) %>% 
  summarize(n_items_ordered = n()) %>% 
  arrange(desc(n_items_ordered))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of Items Ordered by Aisle

```{r plot_items_order_aisle}
instacart_aisles %>% 
  filter(n_items_ordered > 10000) %>% 
  mutate(aisle = reorder(aisle, n_items_ordered)) %>% 
  plot_ly(x = ~aisle, y = ~n_items_ordered, color = ~aisle, type = "bar")
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Items Ordered by Days Since Prior Order

```{r prior_order_plot}

set.seed(1)

insta = 
instacart %>% 
  group_by(order_id) %>% 
  mutate(
    n_items_per_order = n()
  ) %>% 
  distinct()


insta %>% 
  ungroup() %>% 
  sample_n(5000) %>% 

     plot_ly(
       x = ~days_since_prior_order, y = ~n_items_per_order, type = "scatter", mode = "markers", color = ~n_items_per_order)
```

### Number of Items per Order by Days Since Prior Order

```{r}
instacart %>% 
  mutate(
    order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", "4" = "Thursday", "5" = "Friday", "6" = "Saturday"),
    order_dow = fct_relevel(as.factor(order_dow), c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))) %>% 
  group_by(order_id) %>% 
  mutate(
    n_items_per_order = n()
  ) %>% 
  distinct() %>% 

  plot_ly(
    y = ~n_items_per_order, color = ~order_dow, type = "box")
```

