name: "Yay internet!"
output_dir: "."
navbar:
  title: "Home"
  right:
    - text: "About Me"
      href: Dashboard.html
    - icon: fa-envelope fa-lg
      href: mailto:<you@youremail.com>
    - icon: fa-github fa-lg
      href: https://tlayouni.github.io/troy_layouni.github.io>/
output:
  html_document:
    theme: journal